### ISSUE TITLE
Slack emoji

### ISSUE THREAD

**Issue by NicolasMahe** [mesg-foundation/aragon#20]
Is this field really required?
If yes, we should put some explanation to what to put inside.

**Comment by blackinno** [comment]
Slack emoji will be optional if this [pull requests](https://github.com/liteflow-services/slack/pull/16) is merged and redeploy slack service then I will update the UI to not required emoji field

**Comment by NicolasMahe** [comment]
deployed with commit https://github.com/liteflow-services/slack/commit/6517467f0e8d4c5ec0dd73ed097d18e8c367dd7f
```
✔ Service deployed with hash "7Xbdgx96z3KRAgGYyYnsCVe6FCpUFbHjW4finVUMXRV2", instance hash "2rgZwXtrAzL5ngGvVouLhGbWXcnRkknh3k87hdJfRhyj" and runner hash "8ZJ24RaEfAS133Wd5t4JL3ChXvixQ7bJNbqRLntEw9H2"
```
