### ISSUE TITLE
[IDEA] Switch from smart contract to liteflow's firebase

### ISSUE THREAD

**Issue by NicolasMahe** [mesg-foundation/aragon#31]
Having a smart contract and synchronize it makes any functionality much harder to implement and there is no way to put data from liteflow to the smart contract without paying transaction fees ourselves, and it makes the integration even more complicated.

The proposition is to replace the smart contract with a direct connection to liteflow's firebase.
Pro:
- easy to add functionality: just put data on firebase and that's it
- easy to fetch up-to-date info (is process is deployed? what is the balance?)
- increase number of user on liteflow

Con:
- requires aragon user to create a liteflow account
  - I don't think asking email and password to aragon user will be ok for the community
  - we could implement a custom oauth system based on ethereum account using signature
- not sure an aragon application can work without a smart contract? I don't know if aragon put hard limit on what the app can access

**Comment by antho1404** [comment]
I'm not sure that would be relevant, by doing that we would basically get rid of the voting to accept/reject the creation of a process, that seems against the philosophy of Aragon apps. 
I'm also not sure it's technically feasible without having to hack with a fake dumb contract that we never call.

As part of the Aragon/MESG application, I'm really not sure that this makes sense but as a separate website that would definitely be great for users that are not necessarily part of the organization but still want to get notified for some actions of this organization.

**Comment by NicolasMahe** [comment]
> by doing that we would basically get rid of the voting to accept/reject the creation of a process

very good point

**Comment by NicolasMahe** [comment]
closing
