### ISSUE TITLE
Prepare app for submission and review

### ISSUE THREAD

**Issue by NicolasMahe** [mesg-foundation/aragon#42]
Make sure the app contains all the required assets (icons, description, etc..) so we can submit it to Aragon for review

**Comment by blackinno** [comment]
Document: [Link](https://hack.aragon.org/docs/app-center-preparing-assets)

- [ ] App menu icon (SVG)
- [ ] Screenshots (PNG)
- [ ] Short description (text only)
- [ ] Long description (Markdown or text)

**Comment by NicolasMahe** [comment]
@blackinno you can ask directly @EmmanuelDrouin for the icon ;)
